### PR TITLE
Tweak duster recipe system and "checkstyle" some things

### PR DESCRIPTION
**Pull request by iTitus**

### CODE REVIEW

**Comment by iTitus** [comment]
This is my idea of the ChancedOutput class, what do you think about it?

**Comment by AEnterprise** [comment]
that it's to late in the evening for this, will take a look at this when i get back from school tomorow

**Comment by AEnterprise** [comment]
also i already started on something like this but not pushed, will have to compare it to what you made of it

**Comment by AEnterprise** [comment]
most of this looks like what i have, i'll have to do the nei stuff though

i don't realy want the recipe managers in an api package that makes it needlessly complex, imc messages would be far better in handeling that stuff, it would unify handeling it all and prevent outdated api's causing issues

**Comment by iTitus** [comment]
The others don't necessarily need to ship the API package

**Comment by AEnterprise** [comment]
don't don't have to, it's even better if they don't do it at all, but still it is done, not eveyone uses apis like they are ment to be used

**Comment by iTitus** [comment]
I personally like the API package. It is clean and abstract, as everything should be ;)

**Comment by iTitus** [comment]
Any update on this?
Maybe an opinion form @BigXplosion ?

**Comment by AEnterprise** [comment]
update: gona redo dusting, not realy in a duster anymore but in world dusting

**Comment by iTitus** [comment]
Sweet ;)

**Pull request closed without merging**
